package constant

var (
	TransferFnSignature          = []byte("transfer(address,uint256)")
	TransferFromFnSignature      = []byte("transferFrom(address,address,uint256)")
	ApproveFnSignature           = []byte("approve(address,uint256)")
	BalanceOfFnSignature         = []byte("balanceOf(address)")
	TotalSupplyFnSignature       = []byte("totalSupply()")
	AllowanceFnSignature         = []byte("allowance(address,address)")
	NameFnSignature              = []byte("name()")
	SymbolFnSignature            = []byte("symbol()")
	DecimalsFnSignature          = []byte("decimals()")
	MintFnSignature              = []byte("mint(address,uint256)")
	BurnFnSignature              = []byte("burn(uint256)")
	BlacklistFnSignature         = []byte("blacklist(address)")
	UnBlacklistFnSignature       = []byte("unBlacklist(address)")
	IsBlacklistedFnSignature     = []byte("isBlacklisted(address)")
	PauseFnSignature             = []byte("pause()")
	UnpauseFnSignature           = []byte("unpause()")
	PausedFnSignature            = []byte("paused()")
	TransferOwnershipFnSignature = []byte("transferOwnership(address)")
	OwnerFnSignature             = []byte("owner()")
	CurrencyFnSignature          = []byte("currency()")
	VersionFnSignature           = []byte("version()")
	MasterMinterFnSignature      = []byte("masterMinter()")
	PauserFnSignature            = []byte("pauser()")
	BlacklisterFnSignature       = []byte("blacklister()")
	ConfigureMinterFnSignature   = []byte("configureMinter(address,uint256)")
	RemoveMinterFnSignature      = []byte("removeMinter(address)")
	MinterAllowanceFnSignature   = []byte("minterAllowance(address)")
	IsMinterFnSignature          = []byte("isMinter(address)")
)
