name: lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      - name: Install ruleguard
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.5
      - id: lint
        name: Run linter
        run: golangci-lint run -c .golangci.yaml
