name: Test

on:
  pull_request:

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"

      - name: Install dependencies
        run: go mod download

      - name: Set env
        run: go env -w GOTOOLCHAIN=go1.26.0+auto

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run Unit Tests
        run: just ut-cov
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ADDRESS: ${{ secrets.ADDRESS }}

      - name: Run Race Tests
        run: just ut-race
        env:
          API_KEY: ${{ secrets.API_KEY }}
          ADDRESS: ${{ secrets.ADDRESS }}

      - name: Upload Unit Test Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: coverage.out
          retention-days: 1

  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"

      - name: Install dependencies
        run: go mod download

      - name: Set env
        run: go env -w GOTOOLCHAIN=go1.26.0+auto

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d # v1.8.0

      - name: Start Anvil Node
        run: |
          anvil --port 8545 &

      - name: Run E2E Tests
        run: just ci-e2e 8545 -timeout 20m

  coverage-report:
    name: Coverage Report
    runs-on: ubuntu-latest
    needs: [unit-test]
    if: always()

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Unit Test Coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-unit

      - name: Coverage Report
        uses: k1LoW/octocov-action@v1
